sudo: required
notifications:
email: false
language: java
#jdk:
#- oraclejdk8
#before_install:
#- sudo add-apt-repository ppa:dns/gnu -y
#- sudo apt-get update -qq
script:
- mvn install -DskipTests=true -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V
- tools/upload.sh target/*.zip target/*.zip.md5 target/*.zip.sha1
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:ci-build)$/
