#!/bin/sh
# Ad hoc wrapper, for development in the source tree ONLY.
# It is not intended for deployment.

JAVA=java
IRPHOME="$(dirname -- "$(readlink -f -- "${0}")" )"
VERSION=`xpath -q -e  '/project/version/text()' ${IRPHOME}/pom.xml`
JAR=${IRPHOME}/target/IrpTransmogrifier-${VERSION}-jar-with-dependencies.jar
CONFIG=${IRPHOME}/src/main/resources/IrpProtocols.xml

exec "${JAVA}" -jar "${JAR}" -c "${CONFIG}" "$@"
