vol+:		Apple: {F=5,PairID=0},	beg=0, end=68
Play (multiple decodes):
Sig1:		NEC1-f16: {D=238,F=95,S=135},	beg=0, end=68
	NEC2-f16: {D=238,F=95,S=135},	beg=0, end=68, reps=1
Sig2:		NEC1-f16: {D=238,F=5,S=135},	beg=68, end=136
	NEC2-f16: {D=238,F=5,S=135},	beg=68, end=136, reps=1
Pause (multiple decodes):
Sig1:		NEC1-f16: {D=238,F=95,S=135},	beg=0, end=68
	NEC2-f16: {D=238,F=95,S=135},	beg=0, end=68, reps=1
Sig2:		NEC1-f16: {D=238,F=5,S=135},	beg=68, end=144, reps=2
