1:	Audiovox: {D=21,F=1},	beg=0, end=265, reps=7
	Proton: {D=21,F=1},	beg=0, end=265, reps=7
	Proton-40: {D=21,F=1},	beg=0, end=265, reps=7
2:	Audiovox: {D=21,F=2},	beg=0, end=189, reps=5
	Proton: {D=21,F=2},	beg=0, end=189, reps=5
	Proton-40: {D=21,F=2},	beg=0, end=189, reps=5
Play:	Audiovox: {D=21,F=14},	beg=0, end=189, reps=5
	Proton: {D=21,F=14},	beg=0, end=189, reps=5
	Proton-40: {D=21,F=14},	beg=0, end=189, reps=5
Pause:	Audiovox: {D=21,F=17},	beg=0, end=189, reps=5
	Proton: {D=21,F=17},	beg=0, end=189, reps=5
	Proton-40: {D=21,F=17},	beg=0, end=189, reps=5
Ch+:	Audiovox: {D=21,F=23},	beg=0, end=227, reps=6
	Proton: {D=21,F=23},	beg=0, end=227, reps=6
	Proton-40: {D=21,F=23},	beg=0, end=227, reps=6
Ch-:	Audiovox: {D=21,F=24},	beg=0, end=227, reps=6
	Proton: {D=21,F=24},	beg=0, end=227, reps=6
	Proton-40: {D=21,F=24},	beg=0, end=227, reps=6
