0:		B&O: {D=0,F=0},	beg=0, end=44
1:		B&O: {D=0,F=1},	beg=0, end=44
2:		B&O: {D=0,F=2},	beg=0, end=44
3:		B&O: {D=0,F=3},	beg=0, end=44
4:		B&O: {D=0,F=4},	beg=0, end=44
5:		B&O: {D=0,F=5},	beg=0, end=44
6:		B&O: {D=0,F=6},	beg=0, end=44
7:		B&O: {D=0,F=7},	beg=0, end=44
8:		B&O: {D=0,F=8},	beg=0, end=44
9:		B&O: {D=0,F=9},	beg=0, end=44
Vol+ (multiple decodes):
Sig1:		B&O: {D=0,F=96},	beg=0, end=44
Sig2:		B&O repeat: {D=0,F=96},	beg=44, end=86
Sig3:		B&O repeat: {D=0,F=96},	beg=86, end=128
Sig4:		B&O: {D=0,F=96},	beg=128, end=172
Vol- (multiple decodes):
Sig1:		B&O: {D=0,F=100},	beg=0, end=44
Sig2:		B&O repeat: {D=0,F=100},	beg=44, end=86
Sig3:		B&O repeat: {D=0,F=100},	beg=86, end=128
Sig4:		B&O: {D=0,F=100},	beg=128, end=172
Mute:		B&O: {D=0,F=13},	beg=0, end=44
Ch+ (multiple decodes):
Sig1:		B&O: {D=0,F=30},	beg=0, end=44
Sig2:		B&O repeat: {D=0,F=114},	beg=44, end=86
Sig3:		B&O: {D=0,F=114},	beg=86, end=130
Ch- (multiple decodes):
Sig1:		B&O: {D=0,F=31},	beg=0, end=44
Sig2:		B&O repeat: {D=0,F=115},	beg=44, end=86
Sig3:		B&O repeat: {D=0,F=115},	beg=86, end=128
Sig4:		B&O: {D=0,F=115},	beg=128, end=172
Power:		B&O: {D=0,F=12},	beg=0, end=44
