0:	B&O: {D=0,F=0},	beg=0, end=43
1:	B&O: {D=0,F=1},	beg=0, end=43
2:	B&O: {D=0,F=2},	beg=0, end=43
3:	B&O: {D=0,F=3},	beg=0, end=43
4:	B&O: {D=0,F=4},	beg=0, end=43
5:	B&O: {D=0,F=5},	beg=0, end=43
6:	B&O: {D=0,F=6},	beg=0, end=43
7:	B&O: {D=0,F=7},	beg=0, end=43
8:	B&O: {D=0,F=8},	beg=0, end=43
9:	B&O: {D=0,F=9},	beg=0, end=43
Vol+:	B&O: {D=0,F=96},	beg=0, end=43	{B&O repeat: {D=0,F=96},	beg=44, end=85	{B&O repeat: {D=0,F=96},	beg=86, end=127	{B&O: {D=0,F=96},	beg=128, end=171}}}
Vol-:	B&O: {D=0,F=100},	beg=0, end=43	{B&O repeat: {D=0,F=100},	beg=44, end=85	{B&O repeat: {D=0,F=100},	beg=86, end=127	{B&O: {D=0,F=100},	beg=128, end=171}}}
Mute:	B&O: {D=0,F=13},	beg=0, end=43
Ch+:	B&O: {D=0,F=30},	beg=0, end=43	{B&O repeat: {D=0,F=114},	beg=44, end=85	{B&O: {D=0,F=114},	beg=86, end=129}}
Ch-:	B&O: {D=0,F=31},	beg=0, end=43	{B&O repeat: {D=0,F=115},	beg=44, end=85	{B&O repeat: {D=0,F=115},	beg=86, end=127	{B&O: {D=0,F=115},	beg=128, end=171}}}
Power:	B&O: {D=0,F=12},	beg=0, end=43
