unnamed_0:		Bose: {F=14},	beg=0, end=216, reps=6
unnamed_1:		Bose: {F=129},	beg=0, end=180, reps=5
unnamed_2:		Bose: {F=130},	beg=0, end=180, reps=5
unnamed_3:		Bose: {F=128},	beg=0, end=180, reps=5
unnamed_4:		Bose: {F=176},	beg=0, end=180, reps=5
unnamed_5:		Bose: {F=112},	beg=0, end=216, reps=6
unnamed_6 (multiple decodes):
Sig1:		Bose: {F=240},	beg=0, end=180, reps=5
Sig2:		Bose: {F=3},	beg=180, end=468, reps=8
unnamed_7:		Bose: {F=2},	beg=0, end=216, reps=6
unnamed_8:		Bose: {F=1},	beg=0, end=252, reps=7
unnamed_9:		Bose: {F=76},	beg=0, end=288, reps=8
unnamed_10:		Bose: {F=14},	beg=0, end=216, reps=6
unnamed_11:		Bose: {F=129},	beg=0, end=180, reps=5
