Power:	CanalSatLD: {D=37,F=11,S=0},	beg=0, end=137, reps=3
0:	CanalSatLD: {D=37,F=10,S=0},	beg=0, end=193, reps=5
1:	
2:	CanalSatLD: {D=37,F=2,S=0},	beg=0, end=239, reps=6
3:	
4:	CanalSatLD: {D=37,F=4,S=0},	beg=0, end=239, reps=6
5:	CanalSatLD: {D=37,F=5,S=0},	beg=0, end=239, reps=6
6:	CanalSatLD: {D=37,F=6,S=0},	beg=0, end=239, reps=6
7:	
8:	
9:	CanalSatLD: {D=37,F=9,S=0},	beg=0, end=239, reps=6
Vol+:	CanalSatLD: {D=37,F=23,S=0},	beg=0, end=137, reps=3
Vol-:	CanalSatLD: {D=37,F=26,S=0},	beg=0, end=129, reps=3
Mute:	CanalSatLD: {D=37,F=24,S=0},	beg=0, end=137, reps=3
Channel+:	CanalSatLD: {D=37,F=25,S=0},	beg=0, end=239, reps=6
Channel-:	CanalSatLD: {D=37,F=28,S=0},	beg=0, end=239, reps=6
Last_channel:	CanalSatLD: {D=37,F=19,S=0},	beg=0, end=239, reps=6
Exit:	CanalSatLD: {D=37,F=19,S=0},	beg=0, end=239, reps=6
Menu:	CanalSatLD: {D=37,F=45,S=0},	beg=0, end=225, reps=6
Program Guide:	
Up:	CanalSatLD: {D=37,F=12,S=0},	beg=0, end=239, reps=6
Down:	CanalSatLD: {D=37,F=13,S=0},	beg=0, end=239, reps=6
Left:	CanalSatLD: {D=37,F=14,S=0},	beg=0, end=239, reps=6
Right:	CanalSatLD: {D=37,F=16,S=0},	beg=0, end=239, reps=6
Select:	CanalSatLD: {D=37,F=15,S=0},	beg=0, end=253, reps=6
Play:	CanalSatLD: {D=37,F=27,S=0},	beg=0, end=137, reps=3
Pause:	CanalSatLD: {D=37,F=27,S=0},	beg=0, end=137, reps=3
Rewind:	CanalSatLD: {D=37,F=33,S=0},	beg=0, end=137, reps=3
Fast Forward:	CanalSatLD: {D=37,F=36,S=0},	beg=0, end=129, reps=3
Stop:	CanalSatLD: {D=37,F=34,S=0},	beg=0, end=129, reps=3
Record:	CanalSatLD: {D=37,F=35,S=0},	beg=0, end=137, reps=3
Red:	CanalSatLD: {D=37,F=29,S=0},	beg=0, end=137, reps=3
Blue:	CanalSatLD: {D=37,F=32,S=0},	beg=0, end=137, reps=3
Green:	CanalSatLD: {D=37,F=30,S=0},	beg=0, end=137, reps=3
Yellow:	CanalSatLD: {D=37,F=31,S=0},	beg=0, end=145, reps=3
Radio:	CanalSatLD: {D=37,F=43,S=0},	beg=0, end=129, reps=3
Teletext:	CanalSatLD: {D=37,F=41,S=0},	beg=0, end=129, reps=3
TV:	CanalSatLD: {D=37,F=20,S=0},	beg=0, end=129, reps=3
