unnamed_0:		CanalSat: {D=1,F=0,S=37,T=1},	beg=0, end=200, reps=4
unnamed_1:		CanalSat: {D=1,F=1,S=37,T=1},	beg=0, end=114, reps=2
unnamed_2:		CanalSat: {D=1,F=2,S=37,T=1},	beg=0, end=76, reps=1
unnamed_3:		CanalSat: {D=1,F=3,S=37,T=0},	beg=0, end=38
unnamed_4:		CanalSat: {D=1,F=4,S=37,T=1},	beg=0, end=190, reps=4
unnamed_5:	
unnamed_6:		CanalSat: {D=1,F=6,S=37,T=1},	beg=0, end=266, reps=6
unnamed_7:		CanalSat: {D=1,F=20,S=37,T=1},	beg=0, end=108, reps=2
unnamed_8:	
unnamed_9:	
