0:		CanalSat: {D=1,S=6,F=0},	beg=0, end=41	{UNDECODED. length=84}
1:		CanalSat: {D=1,S=6,F=1},	beg=0, end=39	{UNDECODED. length=160}
2:		CanalSat: {D=1,S=6,F=2},	beg=0, end=39	{UNDECODED. length=160}
3:		CanalSat: {D=1,S=6,F=3},	beg=0, end=39	{UNDECODED. length=240}
4:		CanalSat: {D=1,S=6,F=4},	beg=0, end=39	{UNDECODED. length=240}
5:	
Vol+:	
Vol-:		CanalSat: {D=1,S=6,F=21},	beg=0, end=35	{UNDECODED. length=144}
Mute:	
