Power:		CanalSatLD: {D=37,S=0,F=11},	beg=0, end=137, reps=3
0:		CanalSatLD: {D=37,S=0,F=10},	beg=0, end=193, reps=5
1:	
2:		CanalSatLD: {D=37,S=0,F=2},	beg=0, end=239, reps=6
3:	
4:		CanalSatLD: {D=37,S=0,F=4},	beg=0, end=239, reps=6
5:		CanalSatLD: {D=37,S=0,F=5},	beg=0, end=239, reps=6
6:		CanalSatLD: {D=37,S=0,F=6},	beg=0, end=239, reps=6
7:	
8:	
9:		CanalSatLD: {D=37,S=0,F=9},	beg=0, end=239, reps=6
Vol+:		CanalSatLD: {D=37,S=0,F=23},	beg=0, end=137, reps=3
Vol-:		CanalSatLD: {D=37,S=0,F=26},	beg=0, end=129, reps=3
Mute:		CanalSatLD: {D=37,S=0,F=24},	beg=0, end=137, reps=3
Channel+:		CanalSatLD: {D=37,S=0,F=25},	beg=0, end=239, reps=6
Channel-:		CanalSatLD: {D=37,S=0,F=28},	beg=0, end=239, reps=6
Last_channel:		CanalSatLD: {D=37,S=0,F=19},	beg=0, end=239, reps=6
Exit:		CanalSatLD: {D=37,S=0,F=19},	beg=0, end=239, reps=6
Menu:		CanalSatLD: {D=37,S=0,F=45},	beg=0, end=225, reps=6
Program Guide:	
Up:		CanalSatLD: {D=37,S=0,F=12},	beg=0, end=239, reps=6
Down:		CanalSatLD: {D=37,S=0,F=13},	beg=0, end=239, reps=6
Left:		CanalSatLD: {D=37,S=0,F=14},	beg=0, end=239, reps=6
Right:		CanalSatLD: {D=37,S=0,F=16},	beg=0, end=239, reps=6
Select:		CanalSatLD: {D=37,S=0,F=15},	beg=0, end=253, reps=6
Play:		CanalSatLD: {D=37,S=0,F=27},	beg=0, end=137, reps=3
Pause:		CanalSatLD: {D=37,S=0,F=27},	beg=0, end=137, reps=3
Rewind:		CanalSatLD: {D=37,S=0,F=33},	beg=0, end=137, reps=3
Fast Forward:		CanalSatLD: {D=37,S=0,F=36},	beg=0, end=129, reps=3
Stop:		CanalSatLD: {D=37,S=0,F=34},	beg=0, end=129, reps=3
Record:		CanalSatLD: {D=37,S=0,F=35},	beg=0, end=137, reps=3
Red:		CanalSatLD: {D=37,S=0,F=29},	beg=0, end=137, reps=3
Blue:		CanalSatLD: {D=37,S=0,F=32},	beg=0, end=137, reps=3
Green:		CanalSatLD: {D=37,S=0,F=30},	beg=0, end=137, reps=3
Yellow:		CanalSatLD: {D=37,S=0,F=31},	beg=0, end=145, reps=3
Radio:		CanalSatLD: {D=37,S=0,F=43},	beg=0, end=129, reps=3
Teletext:		CanalSatLD: {D=37,S=0,F=41},	beg=0, end=129, reps=3
TV:		CanalSatLD: {D=37,S=0,F=20},	beg=0, end=129, reps=3
