ChLevel:		Denon: {D=12,F=175},	beg=0, end=31
DirectionDown:		Denon-K: {D=4,S=1,F=28},	beg=0, end=299, reps=3
DirectionLeft:		Denon-K: {D=4,S=1,F=29},	beg=0, end=299, reps=3
DirectionRight:		Denon-K: {D=4,S=1,F=30},	beg=0, end=299, reps=3
DirectionUp:		Denon-K: {D=4,S=1,F=27},	beg=0, end=299, reps=3
DynamicEq:		Denon-K: {D=4,S=1,F=547},	beg=0, end=299, reps=3
DynamicVolume:		Denon-K: {D=4,S=1,F=545},	beg=0, end=299, reps=3
InputBd:		Denon-K: {D=4,S=1,F=721},	beg=0, end=299, reps=3
InputDock:		Denon-K: {D=4,S=1,F=717},	beg=0, end=299, reps=3
InputDvd:		Denon-K: {D=4,S=1,F=720},	beg=0, end=299, reps=3
InputGame:		Denon-K: {D=4,S=1,F=725},	beg=0, end=299, reps=3
InputiPod:		Denon-K: {D=4,S=1,F=667},	beg=0, end=299, reps=3
InputMode:		Denon: {D=12,F=182},	beg=0, end=159, reps=2	{Denon{2}: {D=12,F=182},	beg=160, end=191, reps=1}
InputSat/Cbl:		Denon-K: {D=4,S=1,F=723},	beg=0, end=299, reps=3
InputSatTu:		Denon-K: {D=4,S=1,F=696},	beg=0, end=299, reps=3
InputTuner:		Denon-K: {D=4,S=1,F=719},	beg=0, end=299, reps=3
InputTv:		Denon-K: {D=4,S=1,F=722},	beg=0, end=299, reps=3
InputV-Aux:		Denon-K: {D=4,S=1,F=729},	beg=0, end=299, reps=3
iPodFastForward:		Denon-K: {D=4,S=1,F=979},	beg=0, end=299, reps=3
iPodNextTrack:		Denon-K: {D=4,S=1,F=946},	beg=0, end=299, reps=3
iPodPause:		Denon-K: {D=4,S=1,F=947},	beg=0, end=299, reps=3
iPodPlay:		Denon-K: {D=4,S=1,F=992},	beg=0, end=299, reps=3
iPodPreviousTrack:		Denon-K: {D=4,S=1,F=945},	beg=0, end=299, reps=3
iPodRewind:		Denon-K: {D=4,S=1,F=976},	beg=0, end=299, reps=3
Menu:		Denon-K: {D=4,S=1,F=35},	beg=0, end=299, reps=3
ModeDirect/Stereo:		Denon-K: {D=4,S=1,F=305},	beg=0, end=299, reps=3
ModeSimulation:		Denon: {D=2,F=230},	beg=0, end=159, reps=2	{Denon{2}: {D=2,F=230},	beg=160, end=191, reps=1}
ModeStandard:		Denon: {D=2,F=228},	beg=0, end=159, reps=2	{Denon{2}: {D=2,F=228},	beg=160, end=191, reps=1}
MultiEq:		Denon: {D=4,F=157},	beg=0, end=159, reps=2	{Denon{2}: {D=4,F=157},	beg=160, end=191, reps=1}
Mute:		Denon-K: {D=4,S=1,F=370},	beg=0, end=299, reps=3
PowerOff:		Denon-K: {D=4,S=1,F=3},	beg=0, end=299, reps=3
PowerToggle:		Denon-K: {D=4,S=1,F=2},	beg=0, end=299, reps=3
PresetNext:		Denon-K: {D=4,S=1,F=973},	beg=0, end=299, reps=3
PresetPrev:		Denon-K: {D=4,S=1,F=972},	beg=0, end=299, reps=3
Restorer:		Denon-K: {D=4,S=1,F=548},	beg=0, end=299, reps=3
Return:		Denon-K: {D=4,S=1,F=34},	beg=0, end=299, reps=3
Search:		Denon-K: {D=4,S=1,F=983},	beg=0, end=299, reps=3
Select/Ok:		Denon-K: {D=4,S=1,F=31},	beg=0, end=299, reps=3
Sleep:		Denon-K: {D=4,S=1,F=836},	beg=0, end=299, reps=3
Source:		Denon-K: {D=4,S=1,F=693},	beg=0, end=299, reps=3
TuneDown:		Denon-K: {D=4,S=1,F=995},	beg=0, end=299, reps=3
TunerBand:		Denon: {D=12,F=215},	beg=0, end=159, reps=2	{Denon{2}: {D=12,F=215},	beg=160, end=191, reps=1}
TunerMemory:		Denon: {D=12,F=76},	beg=0, end=159, reps=2	{Denon{2}: {D=12,F=76},	beg=160, end=191, reps=1}
TunerShift:		Denon: {D=12,F=205},	beg=0, end=159, reps=2	{Denon{2}: {D=12,F=205},	beg=160, end=191, reps=1}
TuneUp:		Denon-K: {D=4,S=1,F=996},	beg=0, end=299, reps=3
VideoSelect:		Denon: {D=2,F=216},	beg=0, end=159, reps=2	{Denon{2}: {D=2,F=216},	beg=160, end=191, reps=1}
VolumeDown:		Denon-K: {D=4,S=1,F=369},	beg=0, end=299, reps=3
VolumeUp:		Denon-K: {D=4,S=1,F=368},	beg=0, end=299, reps=3
0:		Denon-K: {D=4,S=1,F=25},	beg=0, end=299, reps=3
1:		Denon-K: {D=4,S=1,F=16},	beg=0, end=299, reps=3
2:		Denon-K: {D=4,S=1,F=17},	beg=0, end=299, reps=3
3:		Denon-K: {D=4,S=1,F=18},	beg=0, end=299, reps=3
4:		Denon-K: {D=4,S=1,F=19},	beg=0, end=299, reps=3
5:		Denon-K: {D=4,S=1,F=20},	beg=0, end=299, reps=3
6:		Denon-K: {D=4,S=1,F=21},	beg=0, end=299, reps=3
7:		Denon-K: {D=4,S=1,F=22},	beg=0, end=299, reps=3
8:		Denon-K: {D=4,S=1,F=23},	beg=0, end=299, reps=3
9:		Denon-K: {D=4,S=1,F=24},	beg=0, end=299, reps=3
