0:	Dgtec: {D=129,F=0},	beg=0, end=51	{Dgtec: {D=129,F=0},	beg=52, end=103	{Dgtec: {D=129,F=0},	beg=104, end=155	{Dgtec: {D=129,F=0},	beg=156, end=207}}}
1:	Dgtec: {D=129,F=1},	beg=0, end=51	{Dgtec: {D=129,F=1},	beg=52, end=103	{Dgtec: {D=129,F=1},	beg=104, end=155	{Dgtec: {D=129,F=1},	beg=156, end=207	{Dgtec: {D=129,F=1},	beg=208, end=259}}}}
2:	Dgtec: {D=129,F=2},	beg=0, end=51
3:	Dgtec: {D=129,F=3},	beg=0, end=51	{Dgtec: {D=129,F=3},	beg=52, end=103}
4:	Dgtec: {D=129,F=4},	beg=0, end=51
5:	Dgtec: {D=129,F=5},	beg=0, end=51	{Dgtec: {D=129,F=5},	beg=52, end=103}
Vol+:	Dgtec: {D=129,F=20},	beg=0, end=51	{Dgtec: {D=129,F=20},	beg=52, end=103	{Dgtec: {D=129,F=20},	beg=104, end=155	{Dgtec: {D=129,F=20},	beg=156, end=207	{Dgtec: {D=129,F=20},	beg=208, end=259}}}}
Vol-:	Dgtec: {D=129,F=21},	beg=0, end=51	{Dgtec: {D=129,F=21},	beg=52, end=103	{Dgtec: {D=129,F=21},	beg=104, end=155	{Dgtec: {D=129,F=21},	beg=156, end=207}}}
