0:	Dgtec: {D=129,F=0},	beg=0, end=67, reps=4
1:	Dgtec: {D=129,F=1},	beg=0, end=79, reps=7
2:	Dgtec: {D=129,F=2},	beg=0, end=55, reps=1
3:	Dgtec: {D=129,F=3},	beg=0, end=51
4:	Dgtec: {D=129,F=4},	beg=0, end=51
5:	Dgtec: {D=129,F=5},	beg=0, end=67, reps=4
6:	Dgtec: {D=129,F=6},	beg=0, end=67, reps=4
7:	Dgtec: {D=129,F=7},	beg=0, end=71, reps=5
8:	Dgtec: {D=129,F=8},	beg=0, end=59, reps=2
9:	Dgtec: {D=129,F=9},	beg=0, end=71, reps=5
Vol+:	Dgtec: {D=129,F=20},	beg=0, end=63, reps=3
Vol-:	Dgtec: {D=129,F=21},	beg=0, end=75, reps=6
Mute:	Dgtec: {D=129,F=22},	beg=0, end=67, reps=4
Ch+:	Dgtec: {D=129,F=126},	beg=0, end=59, reps=2
Ch-:	Dgtec: {D=129,F=127},	beg=0, end=67, reps=4
