Power:	Digivision: {D=79,Dev2=67,Dev3=78,F=15},	beg=0, end=89, reps=1
0:	
1:	Digivision: {D=79,Dev2=67,Dev3=78,F=33},	beg=0, end=109, reps=6
2:	Digivision: {D=79,Dev2=67,Dev3=78,F=35},	beg=0, end=109, reps=6
3:	
4:	Digivision: {D=79,Dev2=67,Dev3=78,F=29},	beg=0, end=105, reps=5	{UNDECODED. length=2}
5:	Digivision: {D=79,Dev2=67,Dev3=78,F=30},	beg=0, end=109, reps=6
6:	
7:	Digivision: {D=79,Dev2=67,Dev3=78,F=32},	beg=0, end=105, reps=5	{UNDECODED. length=2}
8:	Digivision: {D=79,Dev2=67,Dev3=78,F=17},	beg=0, end=105, reps=5	{UNDECODED. length=2}
9:	Digivision: {D=79,Dev2=67,Dev3=78,F=18},	beg=0, end=109, reps=6
Vol+:	Digivision: {D=79,Dev2=67,Dev3=78,F=13},	beg=0, end=89, reps=1
Vol-:	Digivision: {D=79,Dev2=67,Dev3=78,F=45},	beg=0, end=89, reps=1
Mute:	Digivision: {D=79,Dev2=67,Dev3=78,F=12},	beg=0, end=89, reps=1
Ch+:	
Ch-:	Digivision: {D=79,Dev2=67,Dev3=78,F=47},	beg=0, end=109, reps=6
Last_ch:	Digivision: {D=79,Dev2=67,Dev3=78,F=24},	beg=0, end=109, reps=6
Exit:	
Menu:	
Guide:	Digivision: {D=79,Dev2=67,Dev3=78,F=48},	beg=0, end=109, reps=6
Display:	Digivision: {D=79,Dev2=67,Dev3=78,F=27},	beg=0, end=109, reps=6
Up:	
Down:	Digivision: {D=79,Dev2=67,Dev3=78,F=37},	beg=0, end=93, reps=2	{UNDECODED. length=2}
Left:	Digivision: {D=79,Dev2=67,Dev3=78,F=41},	beg=0, end=109, reps=6
Right:	Digivision: {D=79,Dev2=67,Dev3=78,F=40},	beg=0, end=109, reps=6
Select:	Digivision: {D=79,Dev2=67,Dev3=78,F=44},	beg=0, end=109, reps=6
Page+:	
Page-:	
Return:	Digivision: {D=79,Dev2=67,Dev3=78,F=11},	beg=0, end=89, reps=1
Red:	
Green:	
Yellow:	
Blue:	
