Page+:	Digivision: {D=79,Dev2=67,Dev3=78,F=28},	beg=0, end=109, reps=6
Page-:	
0:	Digivision: {D=79,Dev2=67,Dev3=78,F=19},	beg=0, end=109, reps=6
3:	Digivision: {D=79,Dev2=67,Dev3=78,F=34},	beg=0, end=109, reps=6
6:	Digivision: {D=79,Dev2=67,Dev3=78,F=18},	beg=0, end=109, reps=6
Ch+:	Digivision: {D=79,Dev2=67,Dev3=78,F=46},	beg=0, end=109, reps=6
Exit:	Digivision: {D=79,Dev2=67,Dev3=78,F=14},	beg=0, end=109, reps=6
Up:	Digivision: {D=79,Dev2=67,Dev3=78,F=43},	beg=0, end=109, reps=6
