0:		Dishplayer: {F=17,S=0,D=3},	beg=0, end=253, reps=8
1:		Dishplayer: {F=4,S=0,D=3},	beg=0, end=141, reps=4
2:		Dishplayer: {F=5,S=0,D=3},	beg=0, end=365, reps=12
3:		Dishplayer: {F=6,S=0,D=3},	beg=0, end=113, reps=3
4:		Dishplayer: {F=8,S=0,D=3},	beg=0, end=29
5:		Dishplayer: {F=9,S=0,D=3},	beg=0, end=169, reps=5
6:		Dishplayer: {F=10,S=0,D=3},	beg=0, end=85, reps=2
7:		Dishplayer: {F=12,S=0,D=3},	beg=0, end=281, reps=9
8:	
9:		Dishplayer: {F=14,S=0,D=3},	beg=0, end=393, reps=13
up:		Dishplayer: {F=26,S=0,D=3},	beg=0, end=85, reps=2
down:		Dishplayer: {F=30,S=0,D=3},	beg=0, end=197, reps=6
left:		Dishplayer: {F=28,S=0,D=3},	beg=0, end=449, reps=15
right:		Dishplayer: {F=24,S=0,D=3},	beg=0, end=365, reps=12
OK:		Dishplayer: {F=16,S=0,D=3},	beg=0, end=309, reps=10
