unnamed_0:		Dish_Network: {F=17,S=0,D=0},	beg=0, end=103, reps=2
unnamed_1:		Dish_Network: {F=4,S=0,D=0},	beg=0, end=103, reps=2
unnamed_2:		Dish_Network: {F=5,S=0,D=0},	beg=0, end=137, reps=3
unnamed_3:		Dish_Network: {F=6,S=0,D=0},	beg=0, end=69, reps=1
unnamed_4:		Dish_Network: {F=8,S=0,D=0},	beg=0, end=69, reps=1
unnamed_5:		Dish_Network: {F=26,S=0,D=0},	beg=0, end=103, reps=2
unnamed_6:	
unnamed_7:	
unnamed_8:		Dish_Network: {F=24,S=0,D=0},	beg=0, end=69, reps=1
