0:	Dishplayer: {D=3,F=17,S=0},	beg=0, end=253, reps=8
1:	Dishplayer: {D=3,F=4,S=0},	beg=0, end=141, reps=4
2:	Dishplayer: {D=3,F=5,S=0},	beg=0, end=365, reps=12
3:	Dishplayer: {D=3,F=6,S=0},	beg=0, end=113, reps=3
4:	Dishplayer: {D=3,F=8,S=0},	beg=0, end=29
5:	Dishplayer: {D=3,F=9,S=0},	beg=0, end=169, reps=5
6:	Dishplayer: {D=3,F=10,S=0},	beg=0, end=85, reps=2
7:	Dishplayer: {D=3,F=12,S=0},	beg=0, end=281, reps=9
8:	
9:	Dishplayer: {D=3,F=14,S=0},	beg=0, end=393, reps=13
up:	Dishplayer: {D=3,F=26,S=0},	beg=0, end=85, reps=2
down:	Dishplayer: {D=3,F=30,S=0},	beg=0, end=197, reps=6
left:	Dishplayer: {D=3,F=28,S=0},	beg=0, end=449, reps=15
right:	Dishplayer: {D=3,F=24,S=0},	beg=0, end=365, reps=12
OK:	Dishplayer: {D=3,F=16,S=0},	beg=0, end=309, reps=10
