0:		Dishplayer: {D=3,F=17,S=0},	beg=0, end=254, reps=8
1:		Dishplayer: {D=3,F=4,S=0},	beg=0, end=142, reps=4
2:		Dishplayer: {D=3,F=5,S=0},	beg=0, end=366, reps=12
3:		Dishplayer: {D=3,F=6,S=0},	beg=0, end=114, reps=3
4:		Dishplayer: {D=3,F=8,S=0},	beg=0, end=30
5:		Dishplayer: {D=3,F=9,S=0},	beg=0, end=170, reps=5
6:		Dishplayer: {D=3,F=10,S=0},	beg=0, end=86, reps=2
7:		Dishplayer: {D=3,F=12,S=0},	beg=0, end=282, reps=9
8:	
9:		Dishplayer: {D=3,F=14,S=0},	beg=0, end=394, reps=13
up:		Dishplayer: {D=3,F=26,S=0},	beg=0, end=86, reps=2
down:		Dishplayer: {D=3,F=30,S=0},	beg=0, end=198, reps=6
left:		Dishplayer: {D=3,F=28,S=0},	beg=0, end=450, reps=15
right:		Dishplayer: {D=3,F=24,S=0},	beg=0, end=366, reps=12
OK:		Dishplayer: {D=3,F=16,S=0},	beg=0, end=310, reps=10
