POWER ON:		Dyson_relaxed: {D=5,F=0,T=3},	beg=0, end=33, reps=1	{UNDECODED. length=34}
POWER OFF:		Dyson_relaxed: {D=5,F=0},	beg=0, end=33, reps=1	{UNDECODED. length=34}
Oscillate ON:		Dyson_relaxed: {D=5,F=21,T=3},	beg=0, end=33, reps=1	{UNDECODED. length=34}
Oscillate OFF:		Dyson_relaxed: {D=5,F=21},	beg=0, end=33, reps=1	{UNDECODED. length=34}
LESS AIR:		Dyson_relaxed: {D=5,F=63},	beg=0, end=33, reps=1	{UNDECODED. length=34}
MORE AIR:		Dyson_relaxed: {D=5,F=42,T=1},	beg=0, end=33, reps=1	{UNDECODED. length=34}
Power On:		Dyson_relaxed: {D=9,F=0,T=2},	beg=0, end=33, reps=1
Power Off:		Dyson_relaxed: {D=9,F=0},	beg=0, end=33, reps=1
increase heat:		Dyson_relaxed: {D=9,F=30,T=2},	beg=0, end=33, reps=1
decrease heat:		Dyson_relaxed: {D=9,F=51},	beg=0, end=33, reps=1
oscillating on:		Dyson_relaxed: {D=9,F=21},	beg=0, end=33, reps=1
oscillating off:		Dyson_relaxed: {D=9,F=21,T=2},	beg=0, end=33, reps=1
Dyson decrease fan speed:		Dyson_relaxed: {D=9,F=63,T=2},	beg=0, end=33, reps=1
Dyson increase fan speed:		Dyson_relaxed: {D=9,F=42,T=2},	beg=0, end=33, reps=1
