POWER ON:	Dysan: {D=5,F=192},	beg=0, end=33, reps=1	{UNDECODED. length=34}
POWER OFF:	Dysan: {D=5,F=0},	beg=0, end=33, reps=1	{UNDECODED. length=34}
Oscillate ON:	Dysan: {D=5,F=213},	beg=0, end=33, reps=1	{UNDECODED. length=34}
Oscillate OFF:	Dysan: {D=5,F=21},	beg=0, end=33, reps=1	{UNDECODED. length=34}
LESS AIR:	Dysan: {D=5,F=63},	beg=0, end=33, reps=1	{UNDECODED. length=34}
MORE AIR:	Dysan: {D=5,F=170},	beg=0, end=33, reps=1	{UNDECODED. length=34}
Power On:	Dysan: {D=9,F=64},	beg=0, end=33, reps=1
Power Off:	Dysan: {D=9,F=0},	beg=0, end=33, reps=1
increase heat:	Dysan: {D=9,F=94},	beg=0, end=33, reps=1
decrease heat:	Dysan: {D=9,F=51},	beg=0, end=33, reps=1
oscillating on:	Dysan: {D=9,F=21},	beg=0, end=33, reps=1
oscillating off:	Dysan: {D=9,F=85},	beg=0, end=33, reps=1
Dyson decrease fan speed:	Dysan: {D=9,F=127},	beg=0, end=33, reps=1
Dyson increase fan speed:	Dysan: {D=9,F=106},	beg=0, end=33, reps=1
