Ch1 Mute:	
Ch1 Unmute:	
Ch1 Vol -:	
Ch 1 Vol+:	
Ch1 Power Off:	
Ch1 Power On:	
Ch2 Mute:	
Ch2 Unmute:	
Ch2 Vol-:	
Ch2 Vol+:	
Ch2 Power Off:	
Ch2 Power On:	
Ch3 Mute:	
Ch3 Unmute:	
Ch3 Vol-:	
Ch3 Vol+:	
Ch3 Power Off:	
Ch3 Power On:	
Ch4 Mute:	
Ch4 Unmute:	
Ch4 Vol-:	
Ch4 Vol+:	
Ch4 Power Off:	
Ch4 Power On:	
Ch5 Mute:	
Ch5 Unmute:	
Ch6 Mute:	
Ch7 Mute:	
Ch8 Mute:	
Ch9 Mute:	
Ch10 Mute:	
Ch11 Mute:	
Ch 12 Mute:	
Ch 12 Unmute:	
Ch 12 Vol-:	
Ch12 Vol+:	
Ch12 Power Off:	
Ch 12 Power On:	
Ch 13 Mute:	
Ch 14 Mute:	
Ch 15 Mute:	
Ch 16 Mute:	
try CH2 unmute:	
