s-vid:	Epson: {D=9,F1=3,F2=2,OBC=4,S=5,T1=1,T2=0},	beg=0, end=119, reps=4	{UNDECODED. length=30}
Power:	Epson: {D=9,F1=3,F2=2,OBC=2,S=5,T1=1,T2=0},	beg=0, end=119, reps=4	{UNDECODED. length=30}
search:	Epson: {D=9,F1=2,F2=2,OBC=7,S=5,T1=0,T2=0},	beg=0, end=119, reps=4	{UNDECODED. length=30}
1:	Epson: {D=9,F1=2,F2=2,OBC=0,S=5,T1=0,T2=0},	beg=0, end=89, reps=3	{UNDECODED. length=30}
2:	Epson: {D=9,F1=3,F2=2,OBC=0,S=5,T1=1,T2=0},	beg=0, end=89, reps=3	{UNDECODED. length=30}
3:	Epson: {D=9,F1=3,F2=2,OBC=0,S=5,T1=1,T2=0},	beg=0, end=89, reps=3	{UNDECODED. length=30}
4:	Epson: {D=9,F1=2,F2=2,OBC=3,S=5,T1=0,T2=0},	beg=0, end=89, reps=3	{UNDECODED. length=30}
5:	Epson: {D=9,F1=2,F2=2,OBC=2,S=5,T1=0,T2=0},	beg=0, end=89, reps=3	{UNDECODED. length=30}
6:	Epson: {D=9,F1=3,F2=2,OBC=2,S=5,T1=1,T2=0},	beg=0, end=89, reps=3	{UNDECODED. length=30}
7:	Epson: {D=9,F1=3,F2=2,OBC=3,S=5,T1=1,T2=0},	beg=0, end=89, reps=3	{UNDECODED. length=30}
8:	Epson: {D=9,F1=3,F2=2,OBC=2,S=5,T1=1,T2=0},	beg=0, end=89, reps=3	{UNDECODED. length=30}
9:	Epson: {D=9,F1=2,F2=2,OBC=2,S=5,T1=0,T2=0},	beg=0, end=149, reps=5	{UNDECODED. length=30}
video:	Epson: {D=9,F1=3,F2=2,OBC=4,S=5,T1=1,T2=0},	beg=0, end=89, reps=3	{UNDECODED. length=30}
EZ-MP:	Epson: {D=9,F1=2,F2=2,OBC=5,S=5,T1=0,T2=0},	beg=0, end=89, reps=3	{UNDECODED. length=30}
comp1:	Epson: {D=9,F1=3,F2=2,OBC=5,S=5,T1=1,T2=0},	beg=0, end=89, reps=3	{UNDECODED. length=30}
comp2:	Epson: {D=9,F1=2,F2=2,OBC=5,S=5,T1=0,T2=0},	beg=0, end=119, reps=4	{UNDECODED. length=30}
MENU:	Epson: {D=9,F1=2,F2=2,OBC=2,S=5,T1=0,T2=0},	beg=0, end=89, reps=3	{UNDECODED. length=30}
HELP:	Epson: {D=9,F1=2,F2=2,OBC=2,S=5,T1=0,T2=0},	beg=0, end=119, reps=4	{UNDECODED. length=30}
PG`Down_Arrow:	Epson: {D=9,F1=3,F2=2,OBC=2,S=5,T1=1,T2=0},	beg=0, end=89, reps=3	{UNDECODED. length=30}
E-ZOOM-:	Epson: {D=9,F1=2,F2=2,OBC=2,S=5,T1=0,T2=0},	beg=0, end=89, reps=3	{UNDECODED. length=30}
FREEZE:	Epson: {D=9,F1=3,F2=2,OBC=0,S=5,T1=1,T2=0},	beg=0, end=119, reps=4	{UNDECODED. length=30}
PG`Up_Arrow:	Epson: {D=9,F1=3,F2=2,OBC=2,S=5,T1=1,T2=0},	beg=0, end=89, reps=3	{UNDECODED. length=30}
E-ZOOM+:	Epson: {D=9,F1=2,F2=2,OBC=2,S=5,T1=0,T2=0},	beg=0, end=89, reps=3	{UNDECODED. length=30}
RESIZE:	Epson: {D=9,F1=2,F2=2,OBC=0,S=5,T1=0,T2=0},	beg=0, end=119, reps=4	{UNDECODED. length=30}
A/VMUTE:	Epson: {D=9,F1=3,F2=2,OBC=2,S=5,T1=1,T2=0},	beg=0, end=119, reps=4	{UNDECODED. length=30}
ENTER:	
PnP:	Epson: {D=9,F1=2,F2=2,OBC=2,S=5,T1=0,T2=0},	beg=0, end=119, reps=4	{UNDECODED. length=30}
ESC:	
COLOR MOD:	Epson: {D=9,F1=3,F2=2,OBC=2,S=5,T1=1,T2=0},	beg=0, end=89, reps=3	{UNDECODED. length=30}
