s-vid:		Epson: {D=98,S=170,OBC=18,T1=1,T2=0,F1=1,F2=0},	beg=0, end=119, reps=4	{UNDECODED. length=30}
Power:		Epson: {D=98,S=170,OBC=42,T1=1,T2=2,F1=1,F2=2},	beg=0, end=119, reps=4	{UNDECODED. length=30}
search:		Epson: {D=98,S=170,OBC=63,T1=2,T2=0,F1=2,F2=0},	beg=0, end=119, reps=4	{UNDECODED. length=30}
1:		Epson: {D=98,S=170,OBC=2,T1=2,T2=2,F1=2,F2=2},	beg=0, end=89, reps=3	{UNDECODED. length=30}
2:		Epson: {D=98,S=170,OBC=11,T1=1,T2=2,F1=1,F2=2},	beg=0, end=89, reps=3	{UNDECODED. length=30}
3:		Epson: {D=98,S=170,OBC=1,T1=1,T2=2,F1=1,F2=2},	beg=0, end=89, reps=3	{UNDECODED. length=30}
4:		Epson: {D=98,S=170,OBC=38,T1=2,T2=2,F1=2,F2=2},	beg=0, end=89, reps=3	{UNDECODED. length=30}
5:		Epson: {D=98,S=168,OBC=42,T1=2,T2=0,F1=2,F2=0},	beg=0, end=89, reps=3	{UNDECODED. length=30}
6:		Epson: {D=98,S=168,OBC=41,T1=1,T2=0,F1=1,F2=0},	beg=0, end=89, reps=3	{UNDECODED. length=30}
7:		Epson: {D=98,S=170,OBC=44,T1=1,T2=2,F1=1,F2=2},	beg=0, end=89, reps=3	{UNDECODED. length=30}
8:		Epson: {D=98,S=168,OBC=32,T1=1,T2=0,F1=1,F2=0},	beg=0, end=89, reps=3	{UNDECODED. length=30}
9:		Epson: {D=98,S=168,OBC=35,T1=2,T2=0,F1=2,F2=0},	beg=0, end=149, reps=5	{UNDECODED. length=30}
video:		Epson: {D=98,S=170,OBC=24,T1=1,T2=0,F1=1,F2=0},	beg=0, end=89, reps=3	{UNDECODED. length=30}
EZ-MP:		Epson: {D=98,S=170,OBC=20,T1=2,T2=0,F1=2,F2=0},	beg=0, end=89, reps=3	{UNDECODED. length=30}
comp1:		Epson: {D=98,S=170,OBC=22,T1=1,T2=2,F1=1,F2=2},	beg=0, end=89, reps=3	{UNDECODED. length=30}
comp2:		Epson: {D=98,S=170,OBC=28,T1=2,T2=2,F1=2,F2=2},	beg=0, end=119, reps=4	{UNDECODED. length=30}
MENU:		Epson: {D=98,S=170,OBC=32,T1=2,T2=2,F1=2,F2=2},	beg=0, end=89, reps=3	{UNDECODED. length=30}
HELP:		Epson: {D=98,S=170,OBC=41,T1=2,T2=2,F1=2,F2=2},	beg=0, end=119, reps=4	{UNDECODED. length=30}
PG`Down_Arrow:		Epson: {D=98,S=168,OBC=33,T1=1,T2=2,F1=1,F2=2},	beg=0, end=89, reps=3	{UNDECODED. length=30}
E-ZOOM-:		Epson: {D=98,S=168,OBC=34,T1=2,T2=2,F1=2,F2=2},	beg=0, end=89, reps=3	{UNDECODED. length=30}
FREEZE:		Epson: {D=98,S=170,OBC=0,T1=1,T2=0,F1=1,F2=0},	beg=0, end=119, reps=4	{UNDECODED. length=30}
PG`Up_Arrow:		Epson: {D=98,S=168,OBC=43,T1=1,T2=2,F1=1,F2=2},	beg=0, end=89, reps=3	{UNDECODED. length=30}
E-ZOOM+:		Epson: {D=98,S=168,OBC=40,T1=2,T2=2,F1=2,F2=2},	beg=0, end=89, reps=3	{UNDECODED. length=30}
RESIZE:		Epson: {D=98,S=170,OBC=10,T1=2,T2=0,F1=2,F2=0},	beg=0, end=119, reps=4	{UNDECODED. length=30}
A/VMUTE:		Epson: {D=98,S=170,OBC=33,T1=1,T2=0,F1=1,F2=0},	beg=0, end=119, reps=4	{UNDECODED. length=30}
ENTER:	
PnP:		Epson: {D=98,S=170,OBC=34,T1=2,T2=0,F1=2,F2=0},	beg=0, end=119, reps=4	{UNDECODED. length=30}
ESC:	
COLOR MOD:		Epson: {D=98,S=170,OBC=43,T1=1,T2=0,F1=1,F2=0},	beg=0, end=89, reps=3	{UNDECODED. length=30}
