s-vid:		Epson: {D=9,F1=3,F2=2,OBC=4,S=5,T1=1,T2=0},	beg=0, end=120, reps=4
Power:		Epson: {D=9,F1=3,F2=2,OBC=2,S=5,T1=1,T2=0},	beg=0, end=120, reps=4
search:		Epson: {D=9,F1=2,F2=2,OBC=7,S=5,T1=0,T2=0},	beg=0, end=120, reps=4
1:		Epson: {D=9,F1=2,F2=2,OBC=0,S=5,T1=0,T2=0},	beg=0, end=90, reps=3
2:		Epson: {D=9,F1=3,F2=2,OBC=0,S=5,T1=1,T2=0},	beg=0, end=90, reps=3
3:		Epson: {D=9,F1=3,F2=2,OBC=0,S=5,T1=1,T2=0},	beg=0, end=90, reps=3
4:		Epson: {D=9,F1=2,F2=2,OBC=3,S=5,T1=0,T2=0},	beg=0, end=90, reps=3
5:		Epson: {D=9,F1=2,F2=2,OBC=2,S=5,T1=0,T2=0},	beg=0, end=90, reps=3
6:		Epson: {D=9,F1=3,F2=2,OBC=2,S=5,T1=1,T2=0},	beg=0, end=90, reps=3
7:		Epson: {D=9,F1=3,F2=2,OBC=3,S=5,T1=1,T2=0},	beg=0, end=90, reps=3
8:		Epson: {D=9,F1=3,F2=2,OBC=2,S=5,T1=1,T2=0},	beg=0, end=90, reps=3
9:		Epson: {D=9,F1=2,F2=2,OBC=2,S=5,T1=0,T2=0},	beg=0, end=150, reps=5
video:		Epson: {D=9,F1=3,F2=2,OBC=4,S=5,T1=1,T2=0},	beg=0, end=90, reps=3
EZ-MP:		Epson: {D=9,F1=2,F2=2,OBC=5,S=5,T1=0,T2=0},	beg=0, end=90, reps=3
comp1:		Epson: {D=9,F1=3,F2=2,OBC=5,S=5,T1=1,T2=0},	beg=0, end=90, reps=3
comp2:		Epson: {D=9,F1=2,F2=2,OBC=5,S=5,T1=0,T2=0},	beg=0, end=120, reps=4
MENU:		Epson: {D=9,F1=2,F2=2,OBC=2,S=5,T1=0,T2=0},	beg=0, end=90, reps=3
HELP:		Epson: {D=9,F1=2,F2=2,OBC=2,S=5,T1=0,T2=0},	beg=0, end=120, reps=4
PG`Down_Arrow:		Epson: {D=9,F1=3,F2=2,OBC=2,S=5,T1=1,T2=0},	beg=0, end=90, reps=3
E-ZOOM-:		Epson: {D=9,F1=2,F2=2,OBC=2,S=5,T1=0,T2=0},	beg=0, end=90, reps=3
FREEZE:		Epson: {D=9,F1=3,F2=2,OBC=0,S=5,T1=1,T2=0},	beg=0, end=120, reps=4
PG`Up_Arrow:		Epson: {D=9,F1=3,F2=2,OBC=2,S=5,T1=1,T2=0},	beg=0, end=90, reps=3
E-ZOOM+:		Epson: {D=9,F1=2,F2=2,OBC=2,S=5,T1=0,T2=0},	beg=0, end=90, reps=3
RESIZE:		Epson: {D=9,F1=2,F2=2,OBC=0,S=5,T1=0,T2=0},	beg=0, end=120, reps=4
A/VMUTE:		Epson: {D=9,F1=3,F2=2,OBC=2,S=5,T1=1,T2=0},	beg=0, end=120, reps=4
ENTER:	
PnP:		Epson: {D=9,F1=2,F2=2,OBC=2,S=5,T1=0,T2=0},	beg=0, end=120, reps=4
ESC:	
COLOR MOD:		Epson: {D=9,F1=3,F2=2,OBC=2,S=5,T1=1,T2=0},	beg=0, end=90, reps=3
