power:	
100+:	
subtitles:	
dtv:	
bs/cs:	
mts:	
1:	
2:	
3:	
4:	
5:	
6:	
7:	
8:	
9:	
10/0:	
11:	
12:	
ch+:	
ch-:	
guide (multiple decodes):
Sig1:		GwtS: {CRC=175,D=112,F=239},	beg=0, end=14
Sig2:		Matsui: {D=2,F=2},	beg=14, end=36, reps=1
exit:	
up:	
down:	
left:	
right:	
ok:	
blue:	
red:	
green:	
yellow:	
d:	
info:	
record:	
play:	
recording list:	
rewind:	
pause:	
forward:	
f.rewind:	
stop:	
f.forward:	
link:	
option:	
zoom:	
menu:	
