0:		G.I.Cable: {D=0,F=0},	beg=0, end=48, reps=3
1:		G.I.Cable: {D=0,F=1},	beg=0, end=52, reps=4
2:	
3:	
4:	
5:		G.I.Cable: {D=0,F=5},	beg=0, end=64, reps=7
6:		G.I.Cable: {D=0,F=6},	beg=0, end=72, reps=9
up:		G.I.Cable: {D=0,F=52},	beg=0, end=52, reps=4
down:		G.I.Cable: {D=0,F=53},	beg=0, end=40, reps=1
left:		G.I.Cable: {D=0,F=54},	beg=0, end=36
right:		G.I.Cable: {D=0,F=55},	beg=0, end=36
OK?:	
Play:		G.I.Cable: {D=0,F=27},	beg=0, end=48, reps=3
