0:	G.I.Cable: {D=0,F=0},	beg=0, end=47, reps=3
1:	G.I.Cable: {D=0,F=1},	beg=0, end=51, reps=4
2:	
3:	
4:	
5:	G.I.Cable: {D=0,F=5},	beg=0, end=63, reps=7
6:	G.I.Cable: {D=0,F=6},	beg=0, end=71, reps=9
up:	G.I.Cable: {D=0,F=52},	beg=0, end=51, reps=4
down:	G.I.Cable: {D=0,F=53},	beg=0, end=39, reps=1
left:	G.I.Cable: {D=0,F=54},	beg=0, end=35
right:	G.I.Cable: {D=0,F=55},	beg=0, end=35
OK?:	
Play:	G.I.Cable: {D=0,F=27},	beg=0, end=47, reps=3
