Archive:	Humax 4Phase: {D=7,F=50,S=32},	beg=0, end=79, reps=3
Blue:	Humax 4Phase: {D=7,F=24,S=32},	beg=0, end=79, reps=3
ChannelDown:	Humax 4Phase: {D=7,F=22,S=32},	beg=0, end=79, reps=3
ChannelPrev:	Humax 4Phase: {D=7,F=26,S=32},	beg=0, end=79, reps=3
ChannelUp:	
DirectionDown:	Humax 4Phase: {D=7,F=13,S=32},	beg=0, end=79, reps=3
DirectionLeft:	Humax 4Phase: {D=7,F=14,S=32},	beg=0, end=79, reps=3
DirectionRight:	
DirectionUp:	Humax 4Phase: {D=7,F=12,S=32},	beg=0, end=79, reps=3
Exit:	Humax 4Phase: {D=7,F=46,S=32},	beg=0, end=79, reps=3
FastForward:	
Green:	Humax 4Phase: {D=7,F=28,S=32},	beg=0, end=79, reps=3
Guide:	Humax 4Phase: {D=7,F=52,S=32},	beg=0, end=79, reps=3
Help:	
Info:	Humax 4Phase: {D=7,F=23,S=32},	beg=0, end=79, reps=3
iTV:	Humax 4Phase: {D=7,F=36,S=32},	beg=0, end=79, reps=3
Menu:	Humax 4Phase: {D=7,F=30,S=32},	beg=0, end=79, reps=3
Mute:	Humax 4Phase: {D=7,F=27,S=32},	beg=0, end=71, reps=3
Option:	Humax 4Phase: {D=7,F=31,S=32},	beg=0, end=79, reps=3
Pause:	Humax 4Phase: {D=7,F=44,S=32},	beg=0, end=79, reps=3
Play:	Humax 4Phase: {D=7,F=38,S=32},	beg=0, end=79, reps=3
PowerToggle:	Humax 4Phase: {D=7,F=11,S=32},	beg=0, end=79, reps=3
Record:	Humax 4Phase: {D=7,F=43,S=32},	beg=0, end=79, reps=3
Red:	
Rewind:	Humax 4Phase: {D=7,F=40,S=32},	beg=0, end=87, reps=3
Search:	Humax 4Phase: {D=7,F=25,S=32},	beg=0, end=71, reps=3
Select/Ok:	Humax 4Phase: {D=7,F=15,S=32},	beg=0, end=79, reps=3
Stop:	Humax 4Phase: {D=7,F=42,S=32},	beg=0, end=87, reps=3
Teletext:	Humax 4Phase: {D=7,F=35,S=32},	beg=0, end=79, reps=3
Tv/Radio:	Humax 4Phase: {D=7,F=0,S=32},	beg=0, end=87, reps=3
VolumeDown:	Humax 4Phase: {D=7,F=21,S=32},	beg=0, end=79, reps=3
VolumeUp:	Humax 4Phase: {D=7,F=19,S=32},	beg=0, end=71, reps=3
Yellow:	Humax 4Phase: {D=7,F=17,S=32},	beg=0, end=35, reps=1	{UNDECODED. length=36}
0:	Humax 4Phase: {D=7,F=10,S=32},	beg=0, end=87, reps=3
1:	Humax 4Phase: {D=7,F=1,S=32},	beg=0, end=19	{UNDECODED. length=60}
2:	Humax 4Phase: {D=7,F=2,S=32},	beg=0, end=87, reps=3
3:	Humax 4Phase: {D=7,F=3,S=32},	beg=0, end=79, reps=3
4:	Humax 4Phase: {D=7,F=4,S=32},	beg=0, end=79, reps=3
5:	Humax 4Phase: {D=7,F=5,S=32},	beg=0, end=79, reps=3
6:	Humax 4Phase: {D=7,F=6,S=32},	beg=0, end=79, reps=3
7:	Humax 4Phase: {D=7,F=7,S=32},	beg=0, end=79, reps=3
8:	Humax 4Phase: {D=7,F=8,S=32},	beg=0, end=87, reps=3
9:	Humax 4Phase: {D=7,F=9,S=32},	beg=0, end=79, reps=3
