Power:	Mitsubishi-K: {D=34,F=41,S=4},	beg=0, end=99, reps=1
Video1:	Mitsubishi-K: {D=34,F=86,S=4},	beg=0, end=99, reps=1
Video2:	Mitsubishi-K: {D=34,F=222,S=4},	beg=0, end=99, reps=1
Video3:	Mitsubishi-K: {D=34,F=85,S=4},	beg=0, end=99, reps=1
Vol+:	Mitsubishi-K: {D=34,F=39,S=4},	beg=0, end=99, reps=1
Vol-:	Mitsubishi-K: {D=34,F=175,S=4},	beg=0, end=99, reps=1
Mute:	Mitsubishi-K: {D=34,F=38,S=4},	beg=0, end=99, reps=1
Rgb1:	Mitsubishi-K: {D=34,F=82,S=4},	beg=0, end=99, reps=1
Rgb2:	Mitsubishi-K: {D=34,F=218,S=4},	beg=0, end=99, reps=1
Rgb3:	Mitsubishi-K: {D=34,F=81,S=4},	beg=0, end=99, reps=1
Cont:	Mitsubishi-K: {D=34,F=101,S=4},	beg=0, end=99, reps=1
Bri:	Mitsubishi-K: {D=34,F=116,S=4},	beg=0, end=99, reps=1
V Posi:	Mitsubishi-K: {D=34,F=115,S=4},	beg=0, end=99, reps=1
V Size:	Mitsubishi-K: {D=34,F=252,S=4},	beg=0, end=99, reps=1
H Posi:	Mitsubishi-K: {D=34,F=100,S=4},	beg=0, end=99, reps=1
H Size:	Mitsubishi-K: {D=34,F=237,S=4},	beg=0, end=99, reps=1
Adjust Up:	Mitsubishi-K: {D=34,F=64,S=4},	beg=0, end=99, reps=1
Adjust Down:	Mitsubishi-K: {D=34,F=200,S=4},	beg=0, end=99, reps=1
Func Up:	Mitsubishi-K: {D=34,F=71,S=4},	beg=0, end=99, reps=1
Func Down:	Mitsubishi-K: {D=34,F=207,S=4},	beg=0, end=99, reps=1
Menu:	Mitsubishi-K: {D=34,F=56,S=4},	beg=0, end=99, reps=1
Enter:	Mitsubishi-K: {D=34,F=176,S=4},	beg=0, end=99, reps=1
Cancel:	Mitsubishi-K: {D=34,F=55,S=4},	beg=0, end=99, reps=1
Display:	Mitsubishi-K: {D=34,F=191,S=4},	beg=0, end=99, reps=1
Deg:	Mitsubishi-K: {D=34,F=186,S=4},	beg=0, end=99, reps=1
Reset:	Mitsubishi-K: {D=34,F=50,S=4},	beg=0, end=99, reps=1
Mem/Min:	Mitsubishi-K: {D=34,F=204,S=4},	beg=0, end=99, reps=1
Ch/Plus:	Mitsubishi-K: {D=34,F=68,S=4},	beg=0, end=99, reps=1
1:	Mitsubishi-K: {D=34,F=11,S=4},	beg=0, end=99, reps=1
2:	Mitsubishi-K: {D=34,F=131,S=4},	beg=0, end=99, reps=1
3:	Mitsubishi-K: {D=34,F=10,S=4},	beg=0, end=99, reps=1
4:	Mitsubishi-K: {D=34,F=130,S=4},	beg=0, end=99, reps=1
5:	Mitsubishi-K: {D=34,F=9,S=4},	beg=0, end=99, reps=1
6:	Mitsubishi-K: {D=34,F=129,S=4},	beg=0, end=99, reps=1
7:	Mitsubishi-K: {D=34,F=8,S=4},	beg=0, end=99, reps=1
8:	Mitsubishi-K: {D=34,F=128,S=4},	beg=0, end=99, reps=1
9:	Mitsubishi-K: {D=34,F=26,S=4},	beg=0, end=99, reps=1
0:	Mitsubishi-K: {D=34,F=146,S=4},	beg=0, end=99, reps=1
