power:		NEC: {D=210,F=210,S=43},	beg=0, end=68
ptz:		NEC: {D=210,F=27,S=43},	beg=0, end=68
rec:		NEC: {D=210,F=143,S=43},	beg=0, end=68
1:		NEC: {D=210,F=69,S=43},	beg=0, end=68
2:		NEC: {D=210,F=68,S=43},	beg=0, end=68
3:		NEC: {D=210,F=74,S=43},	beg=0, end=68
4:		NEC: {D=210,F=23,S=43},	beg=0, end=68
5:		NEC: {D=210,F=22,S=43},	beg=0, end=68
6:		NEC: {D=210,F=21,S=43},	beg=0, end=68
7:		NEC: {D=210,F=20,S=43},	beg=0, end=68
8:		NEC: {D=210,F=19,S=43},	beg=0, end=68
9:		NEC: {D=210,F=18,S=43},	beg=0, end=68
0:		NEC: {D=210,F=16,S=43},	beg=0, end=68
info:		NEC: {D=210,F=17,S=43},	beg=0, end=68
menu:		NEC: {D=210,F=14,S=43},	beg=0, end=68
mute:		NEC: {D=210,F=75,S=43},	beg=0, end=68
audio:		NEC: {D=210,F=82,S=43},	beg=0, end=68
search:		NEC: {D=210,F=31,S=43},	beg=0, end=68
up:		NEC: {D=210,F=84,S=43},	beg=0, end=68
down:		NEC: {D=210,F=86,S=43},	beg=0, end=68
left:		NEC: {D=210,F=141,S=43},	beg=0, end=68
right:		NEC: {D=210,F=12,S=43},	beg=0, end=68
select:		NEC: {D=210,F=28,S=43},	beg=0, end=68
vol +:		NEC: {D=210,F=70,S=43},	beg=0, end=68
vol -:		NEC: {D=210,F=5,S=43},	beg=0, end=68
channel -:		NEC: {D=210,F=11,S=43},	beg=0, end=68
channel +:		NEC: {D=210,F=30,S=43},	beg=0, end=68
rew:		NEC: {D=210,F=211,S=43},	beg=0, end=68
fwd:		NEC: {D=210,F=29,S=43},	beg=0, end=68
pause:		NEC: {D=210,F=77,S=43},	beg=0, end=68
stop:		NEC: {D=210,F=8,S=43},	beg=0, end=68
osd:		NEC: {D=210,F=144,S=43},	beg=0, end=68
seq:		NEC: {D=210,F=212,S=43},	beg=0, end=68
log:		NEC: {D=210,F=142,S=43},	beg=0, end=68
cam:		NEC: {D=210,F=138,S=43},	beg=0, end=68
p\t:		NEC: {D=210,F=139,S=43},	beg=0, end=68
z\f:		NEC: {D=210,F=140,S=43},	beg=0, end=68
dis:		NEC: {D=210,F=137,S=43},	beg=0, end=68
