power:	NEC: {D=210,F=210,S=43},	beg=0, end=67
ptz:	NEC: {D=210,F=27,S=43},	beg=0, end=67
rec:	NEC: {D=210,F=143,S=43},	beg=0, end=67
1:	NEC: {D=210,F=69,S=43},	beg=0, end=67
2:	NEC: {D=210,F=68,S=43},	beg=0, end=67
3:	NEC: {D=210,F=74,S=43},	beg=0, end=67
4:	NEC: {D=210,F=23,S=43},	beg=0, end=67
5:	NEC: {D=210,F=22,S=43},	beg=0, end=67
6:	NEC: {D=210,F=21,S=43},	beg=0, end=67
7:	NEC: {D=210,F=20,S=43},	beg=0, end=67
8:	NEC: {D=210,F=19,S=43},	beg=0, end=67
9:	NEC: {D=210,F=18,S=43},	beg=0, end=67
0:	NEC: {D=210,F=16,S=43},	beg=0, end=67
info:	NEC: {D=210,F=17,S=43},	beg=0, end=67
menu:	NEC: {D=210,F=14,S=43},	beg=0, end=67
mute:	NEC: {D=210,F=75,S=43},	beg=0, end=67
audio:	NEC: {D=210,F=82,S=43},	beg=0, end=67
search:	NEC: {D=210,F=31,S=43},	beg=0, end=67
up:	NEC: {D=210,F=84,S=43},	beg=0, end=67
down:	NEC: {D=210,F=86,S=43},	beg=0, end=67
left:	NEC: {D=210,F=141,S=43},	beg=0, end=67
right:	NEC: {D=210,F=12,S=43},	beg=0, end=67
select:	NEC: {D=210,F=28,S=43},	beg=0, end=67
vol +:	NEC: {D=210,F=70,S=43},	beg=0, end=67
vol -:	NEC: {D=210,F=5,S=43},	beg=0, end=67
channel -:	NEC: {D=210,F=11,S=43},	beg=0, end=67
channel +:	NEC: {D=210,F=30,S=43},	beg=0, end=67
rew:	NEC: {D=210,F=211,S=43},	beg=0, end=67
fwd:	NEC: {D=210,F=29,S=43},	beg=0, end=67
pause:	NEC: {D=210,F=77,S=43},	beg=0, end=67
stop:	NEC: {D=210,F=8,S=43},	beg=0, end=67
osd:	NEC: {D=210,F=144,S=43},	beg=0, end=67
seq:	NEC: {D=210,F=212,S=43},	beg=0, end=67
log:	NEC: {D=210,F=142,S=43},	beg=0, end=67
cam:	NEC: {D=210,F=138,S=43},	beg=0, end=67
p\t:	NEC: {D=210,F=139,S=43},	beg=0, end=67
z\f:	NEC: {D=210,F=140,S=43},	beg=0, end=67
dis:	NEC: {D=210,F=137,S=43},	beg=0, end=67
