power:		NEC: {D=210,S=43,F=210},	beg=0, end=67
ptz:		NEC: {D=210,S=43,F=27},	beg=0, end=67
rec:		NEC: {D=210,S=43,F=143},	beg=0, end=67
1:		NEC: {D=210,S=43,F=69},	beg=0, end=67
2:		NEC: {D=210,S=43,F=68},	beg=0, end=67
3:		NEC: {D=210,S=43,F=74},	beg=0, end=67
4:		NEC: {D=210,S=43,F=23},	beg=0, end=67
5:		NEC: {D=210,S=43,F=22},	beg=0, end=67
6:		NEC: {D=210,S=43,F=21},	beg=0, end=67
7:		NEC: {D=210,S=43,F=20},	beg=0, end=67
8:		NEC: {D=210,S=43,F=19},	beg=0, end=67
9:		NEC: {D=210,S=43,F=18},	beg=0, end=67
0:		NEC: {D=210,S=43,F=16},	beg=0, end=67
info:		NEC: {D=210,S=43,F=17},	beg=0, end=67
menu:		NEC: {D=210,S=43,F=14},	beg=0, end=67
mute:		NEC: {D=210,S=43,F=75},	beg=0, end=67
audio:		NEC: {D=210,S=43,F=82},	beg=0, end=67
search:		NEC: {D=210,S=43,F=31},	beg=0, end=67
up:		NEC: {D=210,S=43,F=84},	beg=0, end=67
down:		NEC: {D=210,S=43,F=86},	beg=0, end=67
left:		NEC: {D=210,S=43,F=141},	beg=0, end=67
right:		NEC: {D=210,S=43,F=12},	beg=0, end=67
select:		NEC: {D=210,S=43,F=28},	beg=0, end=67
vol +:		NEC: {D=210,S=43,F=70},	beg=0, end=67
vol -:		NEC: {D=210,S=43,F=5},	beg=0, end=67
channel -:		NEC: {D=210,S=43,F=11},	beg=0, end=67
channel +:		NEC: {D=210,S=43,F=30},	beg=0, end=67
rew:		NEC: {D=210,S=43,F=211},	beg=0, end=67
fwd:		NEC: {D=210,S=43,F=29},	beg=0, end=67
pause:		NEC: {D=210,S=43,F=77},	beg=0, end=67
stop:		NEC: {D=210,S=43,F=8},	beg=0, end=67
osd:		NEC: {D=210,S=43,F=144},	beg=0, end=67
seq:		NEC: {D=210,S=43,F=212},	beg=0, end=67
log:		NEC: {D=210,S=43,F=142},	beg=0, end=67
cam:		NEC: {D=210,S=43,F=138},	beg=0, end=67
p\t:		NEC: {D=210,S=43,F=139},	beg=0, end=67
z\f:		NEC: {D=210,S=43,F=140},	beg=0, end=67
dis:		NEC: {D=210,S=43,F=137},	beg=0, end=67
