Vol+ NEC2:		NEC2: {D=31,F=223},	beg=0, end=271, reps=4
Vol- NEC2:		NEC2: {D=31,F=95},	beg=0, end=203, reps=3
Mute:		NECx2: {D=67,S=83,F=57},	beg=0, end=203, reps=3
Up:		NECx2: {D=67,S=83,F=13},	beg=0, end=271, reps=4
Down:		NECx2: {D=67,S=83,F=21},	beg=0, end=271, reps=4
Left:		NECx-f16: {D=67,S=83,F=37},	beg=0, end=67
Right:		NECx-f16: {D=67,S=83,F=29},	beg=0, end=67
OK:		NECx2: {D=67,S=83,F=5},	beg=0, end=203, reps=3
Play:		NECx1: {D=44,S=44,F=4},	beg=0, end=85, reps=3
Pause:		NECx1: {D=44,S=44,F=79},	beg=0, end=85, reps=3
Rewind:		NECx1: {D=44,S=44,F=6},	beg=0, end=85, reps=3
FFWD:		NECx1: {D=44,S=44,F=7},	beg=0, end=85, reps=3
Stop:		NECx1: {D=44,S=44,F=5},	beg=0, end=73, reps=1
