Vol+ NEC2:		NEC2: {D=31,F=223},	beg=0, end=271, reps=4
Vol- NEC2:		NEC2: {D=31,F=95},	beg=0, end=203, reps=3
Mute:		NECx1: {D=67,F=57,S=83},	beg=0, end=67	{NECx1: {D=67,F=57,S=83},	beg=68, end=135	{NECx1: {D=67,F=57,S=83},	beg=136, end=203	NECx2: {D=67,F=57,S=83},	beg=136, end=203, reps=1}	NECx2: {D=67,F=57,S=83},	beg=68, end=203, reps=2}
	NECx2: {D=67,F=57,S=83},	beg=0, end=203, reps=3
Up:		NECx1: {D=67,F=13,S=83},	beg=0, end=67	{NECx1: {D=67,F=13,S=83},	beg=68, end=135	{NECx1: {D=67,F=13,S=83},	beg=136, end=203	{NECx1: {D=67,F=13,S=83},	beg=204, end=271	NECx2: {D=67,F=13,S=83},	beg=204, end=271, reps=1}	NECx2: {D=67,F=13,S=83},	beg=136, end=271, reps=2}	NECx2: {D=67,F=13,S=83},	beg=68, end=271, reps=3}
	NECx2: {D=67,F=13,S=83},	beg=0, end=271, reps=4
Down:		NECx1: {D=67,F=21,S=83},	beg=0, end=67	{NECx1: {D=67,F=21,S=83},	beg=68, end=135	{NECx1: {D=67,F=21,S=83},	beg=136, end=203	{NECx1: {D=67,F=21,S=83},	beg=204, end=271	NECx2: {D=67,F=21,S=83},	beg=204, end=271, reps=1}	NECx2: {D=67,F=21,S=83},	beg=136, end=271, reps=2}	NECx2: {D=67,F=21,S=83},	beg=68, end=271, reps=3}
	NECx2: {D=67,F=21,S=83},	beg=0, end=271, reps=4
Left:		NECx1: {D=67,F=37,S=83},	beg=0, end=67
	NECx2: {D=67,F=37,S=83},	beg=0, end=67, reps=1
Right:		NECx1: {D=67,F=29,S=83},	beg=0, end=67
	NECx2: {D=67,F=29,S=83},	beg=0, end=67, reps=1
OK:		NECx1: {D=67,F=5,S=83},	beg=0, end=67	{NECx1: {D=67,F=5,S=83},	beg=68, end=135	{NECx1: {D=67,F=5,S=83},	beg=136, end=203	NECx2: {D=67,F=5,S=83},	beg=136, end=203, reps=1}	NECx2: {D=67,F=5,S=83},	beg=68, end=203, reps=2}
	NECx2: {D=67,F=5,S=83},	beg=0, end=203, reps=3
Play:		NECx1: {D=44,F=4,S=44},	beg=0, end=67	{UNDECODED. length=18}
	NECx2: {D=44,F=4,S=44},	beg=0, end=67, reps=1	{UNDECODED. length=18}
Pause:		NECx1: {D=44,F=79,S=44},	beg=0, end=67	{UNDECODED. length=18}
	NECx2: {D=44,F=79,S=44},	beg=0, end=67, reps=1	{UNDECODED. length=18}
Rewind:		NECx1: {D=44,F=6,S=44},	beg=0, end=67	{UNDECODED. length=18}
	NECx2: {D=44,F=6,S=44},	beg=0, end=67, reps=1	{UNDECODED. length=18}
FFWD:		NECx1: {D=44,F=7,S=44},	beg=0, end=67	{UNDECODED. length=18}
	NECx2: {D=44,F=7,S=44},	beg=0, end=67, reps=1	{UNDECODED. length=18}
Stop:		NECx1: {D=44,F=5,S=44},	beg=0, end=67	{UNDECODED. length=6}
	NECx2: {D=44,F=5,S=44},	beg=0, end=67, reps=1	{UNDECODED. length=6}
