1:	NRC17: {D=92,F=1},	beg=0, end=355, reps=9
2:	NRC17: {D=92,F=2},	beg=0, end=247, reps=6
8:	NRC17: {D=92,F=8},	beg=0, end=217, reps=5
9:	NRC17: {D=92,F=9},	beg=0, end=217, reps=5
Up:	NRC17: {D=92,F=14},	beg=0, end=213, reps=6	{UNDECODED. length=34}
Down:	NRC17: {D=92,F=15},	beg=0, end=227, reps=5
Left:	NRC17: {D=92,F=47},	beg=0, end=187, reps=4
Right:	NRC17: {D=92,F=46},	beg=0, end=207, reps=5
OK  (single press):	NRC17: {D=92,F=48},	beg=0, end=97, reps=1
Vol+ (single press):	NRC17: {D=92,F=22},	beg=0, end=95, reps=1
