Power Off:	Panasonic_Old: {D=27,F=28},	beg=0, end=47, reps=1
AU:	Panasonic_Old: {D=27,F=27},	beg=0, end=47, reps=1
Prg:	Panasonic_Old: {D=27,F=26},	beg=0, end=47, reps=1
Rcl:	Panasonic_Old: {D=27,F=31},	beg=0, end=47, reps=1
1:	Panasonic_Old: {D=27,F=16},	beg=0, end=47, reps=1
2:	Panasonic_Old: {D=27,F=17},	beg=0, end=47, reps=1
3:	Panasonic_Old: {D=27,F=18},	beg=0, end=47, reps=1
4:	Panasonic_Old: {D=27,F=19},	beg=0, end=47, reps=1
5:	Panasonic_Old: {D=27,F=20},	beg=0, end=47, reps=1
6:	Panasonic_Old: {D=27,F=21},	beg=0, end=47, reps=1
7:	Panasonic_Old: {D=27,F=22},	beg=0, end=47, reps=1
8:	Panasonic_Old: {D=27,F=23},	beg=0, end=47, reps=1
9:	Panasonic_Old: {D=27,F=24},	beg=0, end=47, reps=1
0:	Panasonic_Old: {D=27,F=25},	beg=0, end=47, reps=1
Ch+:	Panasonic_Old: {D=27,F=29},	beg=0, end=47, reps=1
Ch-:	Panasonic_Old: {D=27,F=30},	beg=0, end=47, reps=1
