Volume-:	Pioneer-Mix: {D0=173,F0=11},	beg=0, end=135
Volume+:	Pioneer-Mix: {D0=173,F0=10},	beg=0, end=135
Mute1:	
Mute2:	
'Answer 1:	
Answer 2:	
Hangup 1:	
Hangup2:	
source:	Pioneer-Mix: {D0=173,F0=26},	beg=0, end=135
Pause:	Pioneer-Mix: {D0=173,F0=88},	beg=0, end=407, reps=4
display1:	
display2:	
left:	Pioneer-Mix: {D0=173,F0=66},	beg=0, end=271, reps=2
List/enter1:	
List/Enter2:	
right:	Pioneer-Mix: {D0=173,F0=67},	beg=0, end=271, reps=2
up:	Pioneer-Mix: {D0=173,F0=64},	beg=0, end=543, reps=6
down:	Pioneer-Mix: {D0=173,F0=65},	beg=0, end=271, reps=2
Band Esc:	Pioneer-Mix: {D0=173,F0=18},	beg=0, end=203, reps=1
