Up:	Samsung-SMT-G: {D=1024,F=6375,S=14},	beg=0, end=233, reps=3
	Samsung36: {D=32,E=7,F=24,S=0},	beg=0, end=233, reps=3
Down:	Samsung-SMT-G: {D=1024,F=39015,S=14},	beg=0, end=233, reps=3
	Samsung36: {D=32,E=7,F=25,S=0},	beg=0, end=233, reps=3
Left:	Samsung-SMT-G: {D=1024,F=55335,S=14},	beg=0, end=311, reps=4
	Samsung36: {D=32,E=7,F=27,S=0},	beg=0, end=311, reps=4
Right:	Samsung-SMT-G: {D=1024,F=22695,S=14},	beg=0, end=623, reps=8
	Samsung36: {D=32,E=7,F=26,S=0},	beg=0, end=623, reps=8
OK:	Samsung-SMT-G: {D=1024,F=14535,S=14},	beg=0, end=77, reps=1
	Samsung36: {D=32,E=7,F=28,S=0},	beg=0, end=77, reps=1
Play:	Samsung-SMT-G: {D=1024,F=10455,S=14},	beg=0, end=233, reps=3
	Samsung36: {D=32,E=7,F=20,S=0},	beg=0, end=233, reps=3
Pause:	Samsung-SMT-G: {D=1024,F=10455,S=14},	beg=0, end=311, reps=4
	Samsung36: {D=32,E=7,F=20,S=0},	beg=0, end=311, reps=4
Rwd:	Samsung-SMT-G: {D=1024,F=18615,S=14},	beg=0, end=77, reps=1
	Samsung36: {D=32,E=7,F=18,S=0},	beg=0, end=77, reps=1
