Up:	Samsung36: {D=32,E=7,F=24,S=0},	beg=0, end=233, reps=3
Down:	Samsung36: {D=32,E=7,F=25,S=0},	beg=0, end=233, reps=3
Left:	Samsung36: {D=32,E=7,F=27,S=0},	beg=0, end=311, reps=4
Right:	Samsung36: {D=32,E=7,F=26,S=0},	beg=0, end=623, reps=8
OK:	Samsung36: {D=32,E=7,F=28,S=0},	beg=0, end=77, reps=1
Play:	Samsung36: {D=32,E=7,F=20,S=0},	beg=0, end=233, reps=3
Pause:	Samsung36: {D=32,E=7,F=20,S=0},	beg=0, end=311, reps=4
Rwd:	Samsung36: {D=32,E=7,F=18,S=0},	beg=0, end=77, reps=1
