Vol+:		Samsung20: {D=1,S=0,F=56},	beg=0, end=263, reps=6
Vol-:		Samsung20: {D=1,S=0,F=57},	beg=0, end=175, reps=4
Mute:		Samsung20: {D=1,S=0,F=52},	beg=0, end=175, reps=4
Up:		Samsung20: {D=1,S=0,F=54},	beg=0, end=263, reps=6
Down:		Samsung20: {D=1,S=0,F=55},	beg=0, end=175, reps=4
Left:		Samsung20: {D=1,S=0,F=57},	beg=0, end=219, reps=5
Right:		Samsung20: {D=1,S=0,F=56},	beg=0, end=219, reps=5
Info:		Samsung20: {D=1,S=0,F=59},	beg=0, end=263, reps=6
