0:		ScAtl-6: {D=58,F=63},	beg=0, end=156, reps=3
1:		ScAtl-6: {D=26,F=63},	beg=0, end=208, reps=4
2:		ScAtl-6: {D=58,F=62},	beg=0, end=208, reps=4
3:		ScAtl-6: {D=26,F=62},	beg=0, end=52, reps=1
4:		ScAtl-6: {D=58,F=61},	beg=0, end=52, reps=1
5:		ScAtl-6: {D=26,F=61},	beg=0, end=312, reps=6
6:		ScAtl-6: {D=58,F=60},	beg=0, end=260, reps=5
7:		ScAtl-6: {D=26,F=60},	beg=0, end=104, reps=2
8:		ScAtl-6: {D=58,F=59},	beg=0, end=156, reps=3
9:		ScAtl-6: {D=26,F=59},	beg=0, end=104, reps=2
Vol+:	
Vol-:	
Ch+:		ScAtl-6: {D=26,F=53},	beg=0, end=988, reps=19
Ch-:		ScAtl-6: {D=58,F=0},	beg=0, end=52, reps=1
something:	
