Power:		Sejin-1-56: {D=0,S=87,F=0},	beg=0, end=209, reps=7
Mute:		Sejin-1-56: {D=0,S=73,F=0},	beg=0, end=237, reps=7
Vol +:		Sejin-1-56: {D=0,S=68,F=2},	beg=0, end=237, reps=7
Vol -:		Sejin-1-56: {D=0,S=84,F=2},	beg=0, end=237, reps=7
Menu:		Sejin-1-56: {D=0,S=83,F=0},	beg=0, end=223, reps=7
Ch +:		Sejin-1-56: {D=0,S=88,F=2},	beg=0, end=237, reps=7
Ch -:		Sejin-1-56: {D=0,S=73,F=2},	beg=0, end=237, reps=7
CS:		Sejin-1-56: {D=0,S=83,F=2},	beg=0, end=223, reps=7
Rewind:		Sejin-1-56: {D=0,S=121,F=0},	beg=0, end=237, reps=7
Play/Pause:		Sejin-1-56: {D=0,S=123,F=0},	beg=0, end=223, reps=7
Stop:		Sejin-1-56: {D=0,S=89,F=0},	beg=0, end=237, reps=7
Fast Forward:		Sejin-1-56: {D=0,S=120,F=0},	beg=0, end=237, reps=7
Back:		Sejin-1-56: {D=0,S=72,F=0},	beg=0, end=223, reps=7
URL:		Sejin-1-56: {D=0,S=84,F=8},	beg=0, end=237, reps=7
Next:		Sejin-1-56: {D=0,S=88,F=0},	beg=0, end=237, reps=7
Up:		Sejin-1-56: {D=0,S=92,F=0},	beg=0, end=223, reps=7
Down:		Sejin-1-56: {D=0,S=82,F=0},	beg=0, end=237, reps=7
Left:		Sejin-1-56: {D=0,S=13,F=0},	beg=0, end=237, reps=7
Right:		Sejin-1-56: {D=0,S=4,F=0},	beg=0, end=237, reps=7
OK:		Sejin-1-56: {D=0,S=11,F=0},	beg=0, end=223, reps=7
Character Input:		Sejin-1-56: {D=0,S=72,F=2},	beg=0, end=237, reps=7
Clear:		Sejin-1-56: {D=0,S=76,F=0},	beg=0, end=223, reps=7
Space:		Sejin-1-56: {D=0,S=5,F=0},	beg=0, end=237, reps=7
1:		Sejin-1-56: {D=0,S=98,F=0},	beg=0, end=237, reps=7
2:		Sejin-1-56: {D=0,S=99,F=0},	beg=0, end=223, reps=7
3:		Sejin-1-56: {D=0,S=100,F=0},	beg=0, end=237, reps=7
4:		Sejin-1-56: {D=0,S=101,F=0},	beg=0, end=237, reps=7
5:		Sejin-1-56: {D=0,S=69,F=0},	beg=0, end=237, reps=7
6:		Sejin-1-56: {D=0,S=70,F=0},	beg=0, end=237, reps=7
7:		Sejin-1-56: {D=0,S=102,F=0},	beg=0, end=223, reps=7
8:		Sejin-1-56: {D=0,S=104,F=0},	beg=0, end=237, reps=7
9:		Sejin-1-56: {D=0,S=105,F=0},	beg=0, end=237, reps=7
0 (Part 1):		Sejin-1-56: {D=0,S=107,F=0},	beg=0, end=255, reps=8
0 (Part 3):		Sejin-1-56: {D=0,S=107,F=0},	beg=0, end=31, reps=1
0 (Part 3)$1:		Sejin-1-56: {D=0,S=107,F=0},	beg=0, end=31, reps=1
*:		Sejin-1-56: {D=0,S=66,F=0},	beg=0, end=237, reps=7
#:		Sejin-1-56: {D=0,S=84,F=0},	beg=0, end=237, reps=7
LEO-NET:		Sejin-1-56: {D=0,S=82,F=2},	beg=0, end=237, reps=7
Help ?:		Sejin-1-56: {D=0,S=68,F=0},	beg=0, end=237, reps=7
