STANDBY:	SIM2: {F=10},	beg=0, end=35
1:	SIM2: {F=1},	beg=0, end=35
2:	SIM2: {F=2},	beg=0, end=35
3:	SIM2: {F=3},	beg=0, end=35
4:	SIM2: {F=4},	beg=0, end=35
5:	SIM2: {F=5},	beg=0, end=35
6:	SIM2: {F=6},	beg=0, end=35
7:	SIM2: {F=7},	beg=0, end=35
8:	SIM2: {F=8},	beg=0, end=35
9:	SIM2: {F=9},	beg=0, end=35
RI2 ??? 1:	SIM2: {F=129},	beg=0, end=35
RI2 ??? 2:	SIM2: {F=130},	beg=0, end=35
RI2 ??? 3:	SIM2: {F=131},	beg=0, end=35
RI2 ??? 4:	SIM2: {F=132},	beg=0, end=35
RI2 ??? 5:	SIM2: {F=133},	beg=0, end=35
RI2 ??? 6:	SIM2: {F=134},	beg=0, end=35
