play:		Ortek_NEClike: {D=213,S=42,F=25},	beg=0, end=79, reps=2
pause:		Ortek_NEClike: {D=213,S=42,F=29},	beg=0, end=79, reps=2
Rewind:		Ortek_NEClike: {D=213,S=42,F=26},	beg=0, end=79, reps=2
FFWD:		Ortek_NEClike: {D=213,S=42,F=27},	beg=0, end=79, reps=2
Up:		Ortek_NEClike: {D=213,S=42,F=18},	beg=0, end=79, reps=2
Down:		Ortek_NEClike: {D=213,S=42,F=19},	beg=0, end=79, reps=2
Left:		Ortek_NEClike: {D=213,S=42,F=20},	beg=0, end=79, reps=2
Right:		Ortek_NEClike: {D=213,S=42,F=21},	beg=0, end=79, reps=2
Pg Up:		Ortek_NEClike: {D=213,S=42,F=5},	beg=0, end=79, reps=2
Pg Dn:		Ortek_NEClike: {D=213,S=42,F=6},	beg=0, end=79, reps=2
