play:	Ortek_NEClike: {D=213,F=25,S=42},	beg=0, end=79, reps=2
pause:	Ortek_NEClike: {D=213,F=29,S=42},	beg=0, end=79, reps=2
Rewind:	Ortek_NEClike: {D=213,F=26,S=42},	beg=0, end=79, reps=2
FFWD:	Ortek_NEClike: {D=213,F=27,S=42},	beg=0, end=79, reps=2
Up:	Ortek_NEClike: {D=213,F=18,S=42},	beg=0, end=79, reps=2
Down:	Ortek_NEClike: {D=213,F=19,S=42},	beg=0, end=79, reps=2
Left:	Ortek_NEClike: {D=213,F=20,S=42},	beg=0, end=79, reps=2
Right:	Ortek_NEClike: {D=213,F=21,S=42},	beg=0, end=79, reps=2
Pg Up:	Ortek_NEClike: {D=213,F=5,S=42},	beg=0, end=79, reps=2
Pg Dn:	Ortek_NEClike: {D=213,F=6,S=42},	beg=0, end=79, reps=2
