Power:		Xiaomi: {D=60,F=204},	beg=0, end=71, reps=3
Exit:		Xiaomi: {D=134,F=7},	beg=0, end=455, reps=19	{UNDECODED. length=4}
Menu:		Xiaomi: {D=134,F=4},	beg=0, end=551, reps=23	{UNDECODED. length=12}
Vol+:		Xiaomi: {D=134,F=14},	beg=0, end=551, reps=23	{UNDECODED. length=12}
Vol-:		Xiaomi: {D=134,F=15},	beg=0, end=551, reps=23	{UNDECODED. length=12}
Up:		Xiaomi: {D=134,F=5},	beg=0, end=551, reps=23	{UNDECODED. length=12}
Down:		Xiaomi: {D=134,F=6},	beg=0, end=551, reps=23	{UNDECODED. length=12}
Left:		Xiaomi: {D=134,F=11},	beg=0, end=551, reps=23	{UNDECODED. length=12}
Right:		Xiaomi: {D=134,F=12},	beg=0, end=551, reps=23	{UNDECODED. length=12}
Select:		Xiaomi: {D=134,F=13},	beg=0, end=551, reps=23	{UNDECODED. length=12}
Home:		Xiaomi: {D=134,F=8},	beg=0, end=71, reps=3
