App:	XMP-1: {D=84,F=84,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=84,S=0,T=8},	beg=0, end=71, reps=1
Blue:	XMP-1: {D=84,F=67,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=67,S=0,T=8},	beg=0, end=71, reps=1
ChannelDown:	XMP-1: {D=84,F=14,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=14,S=0,T=8},	beg=0, end=71, reps=1
ChannelUp:	XMP-1: {D=84,F=13,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=13,S=0,T=8},	beg=0, end=71, reps=1
DirectionDown:	XMP-1: {D=84,F=34,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=34,S=0,T=8},	beg=0, end=71, reps=1
DirectionLeft:	XMP-1: {D=84,F=35,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=35,S=0,T=8},	beg=0, end=71, reps=1
DirectionRight:	XMP-1: {D=84,F=36,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=36,S=0,T=8},	beg=0, end=71, reps=1
DirectionUp:	XMP-1: {D=84,F=33,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=33,S=0,T=8},	beg=0, end=71, reps=1
Display:	XMP-1: {D=84,F=89,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=89,S=0,T=8},	beg=0, end=71, reps=1
FastForward:	XMP-1: {D=84,F=52,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=52,S=0,T=8},	beg=0, end=71, reps=1
Green:	XMP-1: {D=84,F=65,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=65,S=0,T=8},	beg=0, end=71, reps=1
Guide:	XMP-1: {D=84,F=38,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=38,S=0,T=8},	beg=0, end=71, reps=1
Info:	XMP-1: {D=84,F=39,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=39,S=0,T=8},	beg=0, end=71, reps=1
List:	XMP-1: {D=84,F=87,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=87,S=0,T=8},	beg=0, end=71, reps=1
LiveTv:	XMP-1: {D=84,F=80,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=80,S=0,T=8},	beg=0, end=71, reps=1
Menu:	XMP-1: {D=84,F=81,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=81,S=0,T=8},	beg=0, end=71, reps=1
Mute:	XMP-1: {D=84,F=12,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=12,S=0,T=8},	beg=0, end=71, reps=1
Opt:	XMP-1: {D=84,F=83,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=83,S=0,T=8},	beg=0, end=71, reps=1
Pause:	XMP-1: {D=84,F=50,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=50,S=0,T=8},	beg=0, end=71, reps=1
Play:	XMP-1: {D=84,F=51,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=51,S=0,T=8},	beg=0, end=71, reps=1
PowerToggle:	XMP-1: {D=84,F=15,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=15,S=0,T=8},	beg=0, end=71, reps=1
Prev:	XMP-1: {D=84,F=32,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=32,S=0,T=8},	beg=0, end=71, reps=1
Radio:	XMP-1: {D=84,F=88,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=88,S=0,T=8},	beg=0, end=71, reps=1
Record:	XMP-1: {D=84,F=53,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=53,S=0,T=8},	beg=0, end=71, reps=1
RecordingList:	XMP-1: {D=84,F=83,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=83,S=0,T=8},	beg=0, end=71, reps=1
Red:	XMP-1: {D=84,F=64,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=64,S=0,T=8},	beg=0, end=71, reps=1
Rewind:	XMP-1: {D=84,F=49,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=49,S=0,T=8},	beg=0, end=71, reps=1
Select/Ok:	XMP-1: {D=84,F=37,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=37,S=0,T=8},	beg=0, end=71, reps=1
Stop:	XMP-1: {D=84,F=48,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=48,S=0,T=8},	beg=0, end=71, reps=1
Subtitle:	XMP-1: {D=84,F=40,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=40,S=0,T=8},	beg=0, end=71, reps=1
Teletext:	XMP-1: {D=84,F=86,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=86,S=0,T=8},	beg=0, end=71, reps=1
VOD:	XMP-1: {D=84,F=82,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=82,S=0,T=8},	beg=0, end=71, reps=1
VolumeDown:	
VolumeUp:	XMP-1: {D=84,F=10,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=10,S=0,T=8},	beg=0, end=71, reps=1
0:	XMP-1: {D=84,F=0,S=0,T=8},	beg=0, end=71, reps=1
	XMP-2: {D=84,F=0,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=0,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-2: {D=84,F=0,S=0,T=8},	beg=0, end=71, reps=1
1:	XMP-1: {D=84,F=1,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=1,S=0,T=8},	beg=0, end=71, reps=1
2:	XMP-1: {D=84,F=2,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=2,S=0,T=8},	beg=0, end=71, reps=1
3:	XMP-1: {D=84,F=3,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=3,S=0,T=8},	beg=0, end=71, reps=1
4:	XMP-1: {D=84,F=4,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=4,S=0,T=8},	beg=0, end=71, reps=1
5:	XMP-1: {D=84,F=5,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=5,S=0,T=8},	beg=0, end=71, reps=1
6:	XMP-1: {D=84,F=6,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=6,S=0,T=8},	beg=0, end=71, reps=1
7:	XMP-1: {D=84,F=7,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=7,S=0,T=8},	beg=0, end=71, reps=1
8:	XMP-1: {D=84,F=8,S=0,T=8},	beg=0, end=71, reps=1
	XMPff-1: {D=84,F=8,S=0,T=8},	beg=0, end=71, reps=1
9:	
