#!/bin/sh
# Ad hoc wrapper, for development
JAVA=java

VERSION=0.2.1dev
IRPHOME="$(dirname -- "$(readlink -f -- "${0}")" )"
JAR=${IRPHOME}/../target/IrpTransmogrifier-${VERSION}-jar-with-dependencies.jar
CONFIG=${IRPHOME}/../src/main/resources/IrpProtocols.xml
STDIR=${IRPHOME}/../src/main/st
export STDIR

exec "${JAVA}" -jar "${JAR}" -c "${CONFIG}" "$@"
