# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven + Upload

on:
  push:
    branches: [ SchemaFactory_broken ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: SchemaFactory_broken
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B -V install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true package
    - name: List files
      run: ls -l target
    - name: Upload
      env:
          GITHUB_TOKEN: ${{ secrets.CI_UPLOADER }}
      run: common/scripts/upload.sh target/*.zip target/*.md5 target/*.sha*
